# Generated by Django 5.2.4 on 2025-08-12 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_email_verification_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='Enable in-app notifications')),
                ('enable_email', models.BooleanField(default=True, verbose_name='Enable email notifications')),
                ('enable_push', models.BooleanField(default=False, verbose_name='Enable push notifications')),
                ('startup_saved_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='immediate', max_length=20, verbose_name='Startup saved frequency')),
                ('project_followed_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='immediate', max_length=20, verbose_name='Project followed frequency')),
                ('message_received_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='immediate', max_length=20, verbose_name='Message received frequency')),
                ('project_updated_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='daily_digest', max_length=20, verbose_name='Project updated frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Notification Preference',
                'verbose_name_plural': 'User Notification Preferences',
                'indexes': [models.Index(fields=['user'], name='idx_user_preferences_user')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_type', models.CharField(choices=[('startup_saved', 'Startup Saved'), ('project_followed', 'Project Followed'), ('message_received', 'Message Received'), ('project_updated', 'Project Updated')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('triggered_by_type', models.CharField(blank=True, choices=[('investor', 'Investor'), ('startup', 'Startup'), ('system', 'System')], max_length=20, null=True)),
                ('related_startup_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='idx_notif_user_read'), models.Index(fields=['user', 'notification_type', 'created_at'], name='idx_notif_user_type'), models.Index(fields=['triggered_by_user'], name='idx_notif_triggered_by'), models.Index(fields=['related_startup_id'], name='idx_notif_startup'), models.Index(fields=['related_project_id'], name='idx_notif_project'), models.Index(fields=['expires_at'], name='idx_notif_expires')],
            },
        ),
    ]
