# Generated by Django 5.2.4 on 2025-08-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='Enable in-app notifications')),
                ('enable_email', models.BooleanField(default=True, verbose_name='Enable email notifications')),
                ('enable_push', models.BooleanField(default=False, verbose_name='Enable push notifications')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='communications.notificationtype'),
        ),
        migrations.CreateModel(
            name='UserNotificationTypePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='immediate', max_length=20)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='communications.notificationtype')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_preferences', to='communications.usernotificationpreference')),
            ],
            options={
                'verbose_name': 'User Notification Type Preference',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='idx_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='idx_notif_expires'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationtypepreference',
            constraint=models.UniqueConstraint(fields=('user_preference', 'notification_type'), name='unique_user_preference_notification_type'),
        ),
    ]
