# Generated by Django 5.2.4 on 2025-08-14 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique code for the notification type', unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when this notification is sent')),
                ('default_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='immediate', help_text='Default frequency for this notification type', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification type is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Type',
                'verbose_name_plural': 'Notification Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationTypePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_summary', 'Weekly Summary'), ('disabled', 'Disabled')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Notification Type Preference',
            },
        ),
        migrations.AlterModelOptions(
            name='usernotificationpreference',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='usernotificationpreference',
            name='idx_user_preferences_user',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='message_received_frequency',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='project_followed_frequency',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='project_updated_frequency',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='startup_saved_frequency',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='communications.notificationtype'),
        ),
        migrations.AddField(
            model_name='usernotificationtypepreference',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='communications.notificationtype'),
        ),
        migrations.AddField(
            model_name='usernotificationtypepreference',
            name='user_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_preferences', to='communications.usernotificationpreference'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationtypepreference',
            unique_together={('user_preference', 'notification_type')},
        ),
    ]
