# Generated by Django 5.2.4 on 2025-08-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_link',
        ),
    ]
