# Generated by Django 5.2.4 on 2025-09-02 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_notification_related_project_id_and_more'),
        ('projects', '0003_project_milestones_project_technologies_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
