# Generated by Django 5.2.4 on 2025-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_notification_action_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_project_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_startup_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
