# Generated by Django 5.2.4 on 2025-09-01 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_notification_related_project_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationTypePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether email notifications for this type are enabled', verbose_name='Enabled')),
                ('email_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_enabled', to='communications.emailnotificationpreference')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='communications.notificationtype')),
            ],
            options={
                'verbose_name': 'Email Notification Type Preference',
                'verbose_name_plural': 'Email Notification Type Preferences',
                'constraints': [models.UniqueConstraint(fields=('email_preference', 'notification_type'), name='unique_email_preference_notification_type')],
            },
        ),
    ]
