# Generated by Django 5.2.4 on 2025-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_notification_notification_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_user_type',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_triggered_by',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_startup',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_project',
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationtypepreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.URLField(blank=True, help_text='Optional URL for client action (e.g., deep link or page URL)', max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='usernotificationtypepreference',
            constraint=models.UniqueConstraint(fields=('user_preference', 'notification_type'), name='unique_user_preference_notification_type'),
        ),
    ]
