# Generated by Django 5.2.4 on 2025-09-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_emailnotificationpreference_and_more'),
        ('communications', '0004_notification_related_project'),
    ]

    operations = [
    ]
