# Generated by Django 5.2.4 on 2025-09-05 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_merge_20250903_2218'),
        ('projects', '0003_project_milestones_project_technologies_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project'),
        ),
    ]
