# Generated by Django 5.2.4 on 2025-08-07 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.location'),
        ),
        migrations.AddField(
            model_name='startup',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.industry'),
        ),
        migrations.AddField(
            model_name='startup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.location'),
        ),
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL),
        ),
    ]
