# Generated by Django 5.2.4 on 2025-08-03 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.investor'),
        ),
        migrations.AddField(
            model_name='interest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.investor'),
        ),
        migrations.AddField(
            model_name='investortag',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.investor'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='profiles.city'),
        ),
        migrations.AddField(
            model_name='investor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_locations', to='profiles.location'),
        ),
        migrations.AddField(
            model_name='savedstartup',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.investor'),
        ),
        migrations.AddField(
            model_name='startup',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startups', to='profiles.industry'),
        ),
        migrations.AddField(
            model_name='startup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_locations', to='profiles.location'),
        ),
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedstartup',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.startup'),
        ),
        migrations.AddField(
            model_name='interest',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.startup'),
        ),
        migrations.AddField(
            model_name='startupsocialmedia',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.startup'),
        ),
        migrations.AddField(
            model_name='startuptag',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.startup'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_name_38920e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='tags_tag_typ_766b27_idx'),
        ),
        migrations.AddField(
            model_name='startuptag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tag'),
        ),
        migrations.AddField(
            model_name='investortag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('percent__gte', 0), ('percent__lte', 100)), name='percent_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='investor',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_investor_user'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_startup_user'),
        ),
        migrations.AlterUniqueTogether(
            name='savedstartup',
            unique_together={('investor', 'startup')},
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('investor', 'startup')},
        ),
        migrations.AlterUniqueTogether(
            name='startupsocialmedia',
            unique_together={('startup', 'platform')},
        ),
        migrations.AddIndex(
            model_name='startuptag',
            index=models.Index(fields=['startup'], name='startup_tag_startup_5279ce_idx'),
        ),
        migrations.AddIndex(
            model_name='startuptag',
            index=models.Index(fields=['tag'], name='startup_tag_tag_id_562cae_idx'),
        ),
        migrations.AddConstraint(
            model_name='startuptag',
            constraint=models.UniqueConstraint(fields=('startup', 'tag'), name='unique_startup_tag'),
        ),
        migrations.AddIndex(
            model_name='investortag',
            index=models.Index(fields=['investor'], name='investor_ta_investo_0386cb_idx'),
        ),
        migrations.AddIndex(
            model_name='investortag',
            index=models.Index(fields=['tag'], name='investor_ta_tag_id_3786e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='investortag',
            constraint=models.UniqueConstraint(fields=('investor', 'tag'), name='unique_investor_tag'),
        ),
    ]
