# Generated by Django 5.2.4 on 2025-09-02 00:04

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.apps import apps
from django.db.models.signals import post_migrate

def create_default_users(sender, **kwargs):
    User = apps.get_model('users', 'User')
    UserRole = apps.get_model('users', 'UserRole')

    roles = {r.role: r for r in UserRole.objects.all()}

    users_data = [
        {
            "email": "admin@example.com",
            "first_name": "Admin",
            "last_name": "User",
            "password": "admin1234",
            "role": roles.get("admin"),
            "is_active": True,
            "is_staff": True,
            "is_superuser": True,
        },
        {
            "email": "mod@example.com",
            "first_name": "Moderator",
            "last_name": "User",
            "password": "mod1234",
            "role": roles.get("moderator"),
            "is_active": True,
        },
        {
            "email": "user1@example.com",
            "first_name": "User1",
            "last_name": "Test",
            "password": "user1234",
            "role": roles.get("user"),
            "is_active": True,
        },
        {
            "email": "user2@example.com",
            "first_name": "User2",
            "last_name": "Test",
            "password": "user1234",
            "role": roles.get("user"),
            "is_active": True,
        },
    ]

    for udata in users_data:
        if udata["role"] is None:
            continue
        user, created = User.objects.update_or_create(
            email=udata["email"],
            defaults={k: v for k, v in udata.items() if k != "password"}
        )
        if created or not user.check_password(udata["password"]):
            user.password = make_password(udata["password"])
            user.save()

def remove_default_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email__in=[
        "admin@example.com",
        "mod@example.com",
        "user1@example.com",
        "user2@example.com"
    ]).delete()
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users, remove_default_users),
    ]
