# Generated by Django 5.2.4 on 2025-08-18 12:20 (modified for safe migration)

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name='users' AND column_name='is_superuser'
                ) THEN
                    ALTER TABLE users ADD COLUMN is_superuser BOOLEAN NOT NULL DEFAULT FALSE;
                END IF;
            END$$;
            """,
            reverse_sql="""
            ALTER TABLE users DROP COLUMN IF EXISTS is_superuser;
            """
        ),
    ]
