# Generated by Django 5.2.4 on 2025-08-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator'), ('investor', 'Investor'), ('owner', 'Owner')], max_length=20, unique=True),
        ),
    ]
