# Generated by Django 5.2.4 on 2025-08-04 20:48

import django.db.models.deletion
import validation.validate_role
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_userrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=validation.validate_role.get_default_role_id, help_text='Current role of the user', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.userrole'),
        ),
    ]
