# Generated by Django 5.2.4 on 2025-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when the user's email was verified", null=True),
        ),
    ]
