# Generated by Django 5.2.4 on 2025-08-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification email was sent', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Current role of the user', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.userrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when the user's email was verified", null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator')], max_length=20, unique=True),
        ),
    ]
