# Generated by Django 5.2.4 on 2025-09-03 11:50

from decimal import Decimal
from django.db import migrations

def create_default_project(apps, schema_editor):
    User = apps.get_model("users", "User")
    Startup = apps.get_model("startups", "Startup")
    Category = apps.get_model("projects", "Category")
    Project = apps.get_model("projects", "Project")

    category, _ = Category.objects.get_or_create(
        name="AI",
        defaults={"description": "Artificial Intelligence related projects."}
    )

    user1 = User.objects.filter(email="user1@example.com").first()
    if not user1:
        return

    startup = Startup.objects.filter(user=user1).first()
    if not startup:
        return

    if not Project.objects.filter(title="AI Project", startup=startup).exists():
        Project.objects.create(
            startup=startup,
            title="AI Project",
            description="Demo project for User1 startup.",
            status="draft",
            duration=180,
            funding_goal=Decimal("100000.00"),
            current_funding=Decimal("0.00"),
            category=category,
            website="https://user1-startup-project.com",
            email="ai.project@user1-startup.com",
            has_patents=False,
            is_participant=True,
            is_active=True,
        )


def remove_default_project(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(title="AI Project").delete()

    Category = apps.get_model("projects", "Category")
    Category.objects.filter(name="AI").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ("startups", "0004_fill_default_startups"),
    ]

    operations = [
        migrations.RunPython(create_default_project, remove_default_project),
    ]
