# Generated by Django 5.2.4 on 2025-08-29 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.JSONField(blank=True, default=dict, help_text='Project milestones or roadmap'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(blank=True, default='', help_text='Technologies used in the project, comma-separated', max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_fields', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project History',
                'verbose_name_plural': 'Project Histories',
                'db_table': 'project_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
