# Generated by Django 5.2.4 on 2025-08-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='investors.investor'),
        ),
    ]
