# Generated by Django 5.2.4 on 2025-08-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['project'], name='idx_subscription_project'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['investor'], name='idx_subscription_investor'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('investor', 'project'), name='unique_investor_project'),
        ),
    ]
