apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: forum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: ghcr.io/raidriar28/forum-project:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: DB_PORT
          - name: MAX_RETRIES
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: MAX_RETRIES
          - name: SLEEP_DURATION
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: SLEEP_DURATION
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: DB_USER
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: django-config
                key: REDIS_PORT
      imagePullSecrets:
        - name: ghcr-credentials







