apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: forum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
