apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: forum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-storage
  namespace: forum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
