# Generated by Django 5.2.4 on 2025-08-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startups', to='startups.location'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(models.F('city'), models.F('state'), models.F('country'), name='unique_location', violation_error_message='This location already exists.'),
        ),
    ]
