# Generated by Django 5.2.4 on 2025-08-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.OneToOneField(help_text='User who owns this startup', on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['company_name'], name='startups_company_3f6814_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['stage'], name='startups_stage_855eb1_idx'),
        ),
    ]
