# Generated by Django 5.2.4 on 2025-08-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='startup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='startup',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='funding_stage',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='startup',
            name='industries',
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='industries',
            field=models.ManyToManyField(related_name='startups', to='startups.industry'),
        ),
    ]
