# Generated by Django 5.2.4 on 2025-08-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_location_unique_together_and_more'),
        ('startups', '0002_initial'),
    ]

    operations = [
    ]
