
# Generated by Django 5.2.4 on 2025-08-28 14:32
# Generated by Django 5.2.4 on 2025-08-29 22:38
# Generated by Django 5.2.4 on 2025-08-29 22:38

import validation.validate_names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='company_name',
            field=models.CharField(
                max_length=254,
                unique=True,
                validators=[
                    validation.validate_names.validate_company_name,
                    validation.validate_names.validate_latin
                ]
            ),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(
                choices=[
                    ('idea', 'Idea'),
                    ('mvp', 'MVP'),
                    ('seed', 'Seed'),
                    ('launch', 'Launch'),
                    ('scale', 'Scale'),
                    ('exit', 'Exit')
                ],
                default='idea',
                help_text='Current development stage of the startup',
                max_length=20,
                verbose_name='Development Stage'
            ),
        ),
    ]
