# Generated by Django 5.2.4 on 2025-08-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_stage',
            field=models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('growth', 'Growth')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='investment_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='startups.industry'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='startups.location'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
