# Generated by Django 5.2.4 on 2025-08-13 21:21

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional detailed description of the industry', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text='Name of the industry (unique)', max_length=100, unique=True, verbose_name='Industry Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line',
            field=models.CharField(blank=True, help_text='Street address or detailed address line', max_length=254, null=True, verbose_name='Address Line'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, help_text='City of the location', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(help_text='Country of the location', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal or ZIP code', max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, help_text='Region or state of the location', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links as a JSON object', verbose_name='Social Links'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit')], default='idea', help_text='Current development stage of the startup', max_length=20, verbose_name='Development Stage'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.OneToOneField(help_text='User who owns this startup', on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['name'], name='industries_name_285c10_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country'], name='locations_country_7c8456_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='locations_city_278550_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['region'], name='locations_region_c9db38_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['company_name'], name='startups_company_3f6814_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['stage'], name='startups_stage_855eb1_idx'),
        ),
    ]
