# Generated by Django 5.2.4 on 2025-08-18 12:14 (modified for safe migration)

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'unique_location'
                ) THEN
                    ALTER TABLE locations
                    DROP CONSTRAINT unique_location;
                END IF;
            END$$;
            """,
            reverse_sql="""
            -- При откате constraint будет добавлен заново
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'unique_location'
                ) THEN
                    ALTER TABLE locations
                    ADD CONSTRAINT unique_location UNIQUE (city, region, country);
                END IF;
            END$$;
            """
        ),
    ]
