# Generated by Django 5.2.4 on 2025-08-19 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='funding_needed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of funding required by the startup', max_digits=12, verbose_name='Funding Needed'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.ForeignKey(help_text='Industry in which the startup operates', on_delete=django.db.models.deletion.PROTECT, related_name='startups', to='startups.industry', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of the startup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='startups.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='team_size',
            field=models.PositiveIntegerField(default=0, help_text='Number of team members in the startup', verbose_name='Team Size'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry'], name='startups_industr_8d533a_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['funding_needed'], name='startups_funding_4951ba_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['team_size'], name='startups_team_si_f34d46_idx'),
        ),
    ]
