# Generated by Django 5.2.4 on 2025-08-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_industry_created_at_alter_industry_description_and_more'),
        ('startups', '0003_merge_20250814_1346'),
    ]

    operations = [
    ]
