# Generated by Django 5.2.4 on 2025-09-02 00:32

from django.db import migrations

def create_default_startups(apps, schema_editor):
    User = apps.get_model("users", "User")
    Startup = apps.get_model("startups", "Startup")
    Industry = apps.get_model("startups", "Industry")
    Location = apps.get_model("startups", "Location")

    industries = {
        "Technology": Industry.objects.get_or_create(name="Technology")[0],
        "Healthcare": Industry.objects.get_or_create(name="Healthcare")[0],
        "Finance": Industry.objects.get_or_create(name="Finance")[0],
    }

    locations = {
        "SF": Location.objects.get_or_create(country="US", city="San Francisco", region="CA")[0],
        "NY": Location.objects.get_or_create(country="US", city="New York", region="NY")[0],
        "LDN": Location.objects.get_or_create(country="GB", city="London")[0],
    }

    user1 = User.objects.filter(email="user_startup@example.com").first()
    if user1 and not Startup.objects.filter(user=user1).exists():
        Startup.objects.create(
            user=user1,
            company_name="User1 Tech Startup",
            industry=industries["Technology"],
            location=locations["SF"],
            email="user1.startup@example.com",
            founded_year=2023,
            team_size=5,
            stage="idea",
            description="Default startup for User1.",
        )


def remove_default_startups(apps, schema_editor):
    Startup = apps.get_model("startups", "Startup")
    Startup.objects.filter(company_name__icontains="Startup").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0003_alter_startup_company_name_alter_startup_stage"),
        ("users", "0002_fill_default_users"),
    ]

    operations = [
        migrations.RunPython(create_default_startups, remove_default_startups),
    ]
