# Generated by Django 5.2.4 on 2025-08-19 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_funding_needed_alter_startup_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Unknown City', help_text='City of the location', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='team_size',
            field=models.PositiveIntegerField(default=0, help_text='Number of team members in the startup', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Team Size'),
        ),
    ]
