# Generated by Django 5.2.4 on 2025-09-04 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startup_company_name_alter_startup_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='startup',
            new_name='startup_company_name_idx',
            old_name='startups_company_3f6814_idx',
        ),
        migrations.RenameIndex(
            model_name='startup',
            new_name='startup_stage_idx',
            old_name='startups_stage_855eb1_idx',
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry'], name='startup_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['team_size'], name='startup_team_size_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['funding_needed'], name='startup_funding_needed_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['location'], name='startup_location_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['is_verified'], name='startup_is_verified_idx'),
        ),
    ]
