# Generated by Django 5.2.4 on 2025-08-21 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_alter_location_city_alter_startup_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='team_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of team members in the startup', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Team Size'),
        ),
    ]
