# Generated by Django 5.2.4 on 2025-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_alter_startup_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit'), ('seed', 'Seed')], default='idea', help_text='Current development stage of the startup', max_length=20, verbose_name='Development Stage'),
        ),
    ]
