# Generated by Django 5.2.4 on 2025-08-27 22:13

import validation.validate_names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_alter_startup_stage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location',
        ),
        migrations.AlterField(
            model_name='startup',
            name='company_name',
            field=models.CharField(max_length=254, unique=True, validators=[validation.validate_names.validate_company_name, validation.validate_names.validate_latin]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('seed', 'Seed'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit')], default='idea', help_text='Current development stage of the startup', max_length=20, verbose_name='Development Stage'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('city', 'region', 'country'), name='unique_location', violation_error_message='This location already exists.'),
        ),
    ]
