# Generated by Django 5.2.4 on 2025-08-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag. Must be unique.', max_length=100, unique=True)),
                ('tag_type', models.CharField(choices=[('industry', 'Industry'), ('technology', 'Technology'), ('stage', 'Stage'), ('topic', 'Topic'), ('custom', 'Custom')], default='custom', help_text='The category/type of the tag.', max_length=50)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='The number of times this tag has been used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['tag_type', 'name'],
                'indexes': [models.Index(fields=['name'], name='tags_name_38920e_idx'), models.Index(fields=['tag_type'], name='tags_tag_typ_766b27_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestorStartupConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('interest', 'Interest'), ('saved', 'Saved')], max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.startup')),
            ],
            options={
                'verbose_name': 'Investor Startup Connection',
                'verbose_name_plural': 'Investor Startup Connections',
                'db_table': 'investor_startup_connections',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('investor', 'startup', 'relation_type'), name='unique_investor_startup_connection')],
            },
        ),
        migrations.CreateModel(
            name='TaggedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tag')),
            ],
            options={
                'db_table': 'tagged_entities',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tagged_enti_content_c15ba6_idx'), models.Index(fields=['tag'], name='tagged_enti_tag_id_cdfc60_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'content_type', 'object_id'), name='unique_tag_per_entity')],
            },
        ),
    ]
