# Generated by Django 5.2.4 on 2025-08-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startups.industry'),
        ),
        migrations.AddField(
            model_name='investor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startups.location'),
        ),
    ]
