# Generated by Django 5.2.4 on 2025-08-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0002_initial'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this investor', on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='savedstartup',
            name='investor',
            field=models.ForeignKey(db_column='investor_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='saved_startups', to='investors.investor'),
        ),
        migrations.AddField(
            model_name='savedstartup',
            name='startup',
            field=models.ForeignKey(db_column='startup_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='saved_by_investors', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='investor',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, help_text='Startups that this investor has bookmarked.', related_name='bookmarked_by', through='investors.SavedStartup', to='startups.startup', verbose_name='Bookmarked startups'),
        ),
        migrations.AddIndex(
            model_name='savedstartup',
            index=models.Index(fields=['investor', 'startup'], name='saved_investor_startup_idx'),
        ),
        migrations.AddIndex(
            model_name='savedstartup',
            index=models.Index(fields=['status'], name='saved_status_idx'),
        ),
        migrations.AddIndex(
            model_name='savedstartup',
            index=models.Index(fields=['-saved_at'], name='saved_saved_at_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedstartup',
            constraint=models.UniqueConstraint(fields=('investor', 'startup'), name='uniq_investor_startup'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['company_name'], name='investor_company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['stage'], name='investor_stage_idx'),
        ),
    ]
