# Generated by Django 5.2.4 on 2025-08-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this investor', on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['company_name'], name='investor_company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['stage'], name='investor_stage_idx'),
        ),
    ]
