# Generated by Django 5.2.4 on 2025-08-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_initial'),
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('passed', 'Passed')], default='watching', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(db_column='investor_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_startups', to='investors.investor')),
                ('startup', models.ForeignKey(db_column='startup_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_investors', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Saved Startup',
                'verbose_name_plural': 'Saved Startups',
                'db_table': 'saved_startups',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', through='investors.SavedStartup', to='startups.startup'),
        ),
        migrations.AddConstraint(
            model_name='savedstartup',
            constraint=models.UniqueConstraint(fields=('investor', 'startup'), name='uniq_investor_startup'),
        ),
    ]
