# Generated by Django 5.2.4 on 2025-08-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links as a JSON object', verbose_name='Social Links'),
        ),
    ]
