# Generated by Django 5.2.4 on 2025-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit'), ('seed', 'Seed')], default='mvp', help_text='Current development stage of the investor', max_length=20, verbose_name='Stage'),
        ),
    ]
