# Generated by Django 5.2.4 on 2025-08-14 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_initial'),
        ('startups', '0004_alter_industry_created_at_alter_industry_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='fund_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Size of the investor's fund, must not be negative", max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fund Size'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit')], default='mvp', help_text='Current development stage of the investor', max_length=20, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this investor', on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['company_name'], name='investor_company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['stage'], name='investor_stage_idx'),
        ),
    ]
