# Generated by Django 5.2.4 on 2025-08-28 14:32

import django.db.models.deletion
import validation.validate_names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_investor_social_links'),
        ('startups', '0003_alter_startup_company_name_alter_startup_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='company_name',
            field=models.CharField(max_length=254, unique=True, validators=[validation.validate_names.validate_company_name, validation.validate_names.validate_latin]),
        ),
        migrations.AlterField(
            model_name='investor',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('seed', 'Seed'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit')], default='mvp', help_text='Current development stage of the investor', max_length=20, verbose_name='Stage'),
        ),
        migrations.CreateModel(
            name='ViewedStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(help_text='Investor who viewed the startup', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_startups_links', to='investors.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Startup view history',
                'verbose_name_plural': 'Startup view histories',
                'ordering': ['-viewed_at'],
                'unique_together': {('investor', 'startup')},
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='viewed_startups',
            field=models.ManyToManyField(blank=True, help_text='Startups that this investor recently viewed.', related_name='viewed_by', through='investors.ViewedStartup', to='startups.startup', verbose_name='Viewed startups'),
        ),
    ]
