# Generated by Django 5.2.4 on 2025-08-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_savedstartup_investor_bookmarks_and_more'),
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, help_text='Startups that this investor has bookmarked.', related_name='bookmarked_by', through='investors.SavedStartup', to='startups.startup', verbose_name='Bookmarked startups'),
        ),
        migrations.AlterField(
            model_name='savedstartup',
            name='investor',
            field=models.ForeignKey(db_column='investor_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='saved_startups', to='investors.investor'),
        ),
        migrations.AlterField(
            model_name='savedstartup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedstartup',
            name='startup',
            field=models.ForeignKey(db_column='startup_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='saved_by_investors', to='startups.startup'),
        ),
    ]
