# Generated by Django 5.2.4 on 2025-08-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_alter_investor_stage'),
        ('investors', '0004_investor_social_links'),
    ]

    operations = [
    ]
