# Generated by Django 5.2.4 on 2025-09-03 14:38

from django.db import migrations

def create_default_investor(apps, schema_editor):
    Industry = apps.get_model("startups", "Industry")
    Location = apps.get_model("startups", "Location")
    Investor = apps.get_model("investors", "Investor")
    User = apps.get_model("users", "User")

    user2 = User.objects.filter(email="user2@example.com").first()
    industry = Industry.objects.get_or_create(name="Finance")[0]
    location = Location.objects.get_or_create(country="US", city="New York", region="NY")[0]
    if user2 and not Investor.objects.filter(user=user2).exists():
        Investor.objects.create(
            user=user2,
            company_name="User2 Investment Fund",
            industry=industry,        
            location=location,
            stage="mvp",
            fund_size=1000000,
            founded_year=2020,  
            email="investor3@example.com",
            description="Leading investment fund focused on technology and finance startups.",
            website="https://user2fund.example.com",
            team_size=15,       
        )

def remove_default_investor(apps, schema_editor):
    Investor = apps.get_model("investors", "Investor")
    Investor.objects.filter(company_name="User2 Investment Fund").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_alter_investor_company_name_alter_investor_stage'),
        ("users", "0002_fill_default_users"),
    ]

    operations = [
        migrations.RunPython(create_default_investor, remove_default_investor),
    ]
