# Generated by Django 5.2.4 on 2025-08-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_alter_investor_fund_size_alter_investor_stage_and_more'),
        ('investors', '0005_alter_investor_bookmarks_alter_savedstartup_investor_and_more'),
    ]

    operations = [
    ]
