# Generated by Django 5.2.4 on 2025-08-27 22:13

import validation.validate_names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_merge_20250828_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='company_name',
            field=models.CharField(max_length=254, unique=True, validators=[validation.validate_names.validate_company_name, validation.validate_names.validate_latin]),
        ),
        migrations.AlterField(
            model_name='investor',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('seed', 'Seed'), ('launch', 'Launch'), ('scale', 'Scale'), ('exit', 'Exit')], default='mvp', help_text='Current development stage of the investor', max_length=20, verbose_name='Stage'),
        ),
    ]
