# Generated by Django 5.2.4 on 2025-09-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_alter_investor_company_name_alter_investor_stage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewedstartup',
            unique_together=set(),
        ),
    ]
