# Generated by Django 5.2.4 on 2025-09-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_alter_viewedstartup_unique_together'),
        ('projects', '0003_project_milestones_project_technologies_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('interested', 'Interested'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('passed', 'Passed')], default='watching', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(db_column='investor_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='followed_projects_set', to='investors.investor')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='followed_by_investors', to='projects.project')),
            ],
            options={
                'verbose_name': 'Followed Project',
                'verbose_name_plural': 'Followed Projects',
                'db_table': 'followed_projects',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='followed_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects that this investor is following.', related_name='followed_by', through='investors.FollowedProject', to='projects.project', verbose_name='Followed projects'),
        ),
        migrations.AddConstraint(
            model_name='followedproject',
            constraint=models.UniqueConstraint(fields=('investor', 'project'), name='uniq_investor_project'),
        ),
        migrations.AddIndex(
            model_name='followedproject',
            index=models.Index(fields=['investor', 'project'], name='followed_investor_project_idx'),
        ),
        migrations.AddIndex(
            model_name='followedproject',
            index=models.Index(fields=['status'], name='followed_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followedproject',
            index=models.Index(fields=['-followed_at'], name='followed_followed_at_desc_idx'),
        ),
    ]
