# Generated by Django 5.2.4 on 2025-09-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_alter_viewedstartup_unique_together'),
        ('projects', '0003_project_milestones_project_technologies_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this follow relationship is currently active')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_projects', to='investors.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Follow',
                'verbose_name_plural': 'Project Follows',
                'db_table': 'project_follows',
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['investor'], name='idx_project_follow_investor'), models.Index(fields=['project'], name='idx_project_follow_project'), models.Index(fields=['followed_at'], name='idx_project_follow_followed_at'), models.Index(fields=['is_active'], name='idx_project_follow_is_active')],
                'constraints': [models.UniqueConstraint(fields=('investor', 'project'), name='unique_investor_project_follow')],
            },
        ),
    ]
