# Generated by Django 5.2.4 on 2025-08-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_86ea8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_type_8e213d_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications_notification',
        ),
    ]
